// app/constants/projects.js
export const PROJECTS = [
  {
    name: "Portway - Developer Tunneling Platform",
    url: "https://portway.online",
    description:
      "A self-hosted ngrok alternative that exposes local servers to the public internet over secure tunnels with custom subdomains. A FastAPI control plane provisions projects and tunnels, a Go relay moves the bytes, and a Next.js dashboard offers live tunnel status and a real-time request inspector over WebSockets. Freemium with Paystack billing and per-plan tunnel and bandwidth limits.",
    tech: [
      "FastAPI",
      "Go Relay",
      "Next.js",
      "MySQL",
      "Redis & RQ",
      "Paystack",
      "JWT Auth",
      "Docker Compose",
    ],
    impact: "Free: 3 tunnels. Pro: 50 tunnels with encrypted HTTPS/TCP/UDP",
    image: "/projects/portway.png",
    category: "Developer Tools",
    featured: true,
  },
  {
    name: "Snapit - Universal Clipboard Vault",
    url: "https://snapit.ink",
    description:
      "Local-first clipboard manager with unlimited history, tagging, search, and quick-paste hotkeys. Syncs encrypted across desktop and mobile via an optional self-hosted or cloud backend. Freemium: free forever on desktop, Pro unlocks cross-device sync.",
    tech: [
      "Flutter Desktop",
      "Flutter Mobile",
      "Next.js",
      "Flask",
      "MySQL",
      "Redis",
      "SQLite",
      "AES-256-GCM",
    ],
    impact:
      "Free tier: unlimited local history. Pro: encrypted cross-device sync",
    image: "/projects/snap.png",
    category: "Productivity",
    featured: true,
  },
  {
    name: "My Studio - Clients Project Portal",
    url: "https://studio.bennyhinn.life",
    description:
      "A full-stack client project management platform. Built to bring radical transparency and elegance to the studio-client relationship.",
    tech: [
      "Next.js",
      "TailwindCSS",
      "Flask",
      "PostgreSQL",
      "Redis",
      "Redux Toolkit",
    ],
    impact: "Built for: studio.bennyhinn.life",
    image: "/projects/studio.png",
    category: "Workflow & Planning",
    featured: true,
  },
  {
    name: "TabMemory",
    url: "https://tabmemory.smartminds.life",
    description:
      "The accountability-first tab manager for knowledge workers, devs and just any other person. Convert digital clutter into actionable intelligence with TabMemory.",
    tech: [
      "Next.js 16",
      "TailwindCSS",
      "Flask",
      "Redis & Celery",
      "MySQL",
      "M-PESA / Paystack",
      "JWT Auth",
    ],
    impact: "Processing 1000+ memories, 99.9% fulfillment accuracy",
    image: "/projects/tabmemory.png",
    category: "Workflow & Planning",
    featured: true,
  },
  {
    name: "SmartMinds",
    url: "https://www.smartminds.life",
    description:
      "High-performance financial ecosystem digitizing Kenyan savings circles (Chamas) with automated Merry-Go-Round rotations, P2P lending, and MMF yield optimization.",
    tech: [
      "Next.js 16",
      "TailwindCSS",
      "Flask",
      "Redis & Celery",
      "MySQL",
      "M-PESA / Paystack",
      "JWT Auth",
    ],
    impact: "Managing 30+ active Chamas, 99.9% automated ledger accuracy",
    image: "/projects/smartminds.png",
    category: "FinTech",
  },
  {
    name: "Errands By Us",
    url: "https://www.errandsbyus.co.ke",
    description:
      "Focus on what matters most while we handle your errands. Kenya's most trusted errand agency.",
    tech: [
      "Next.js 16",
      "TailwindCSS",
      "Flask",
      "Payment Integration",
      "JWT Auth",
      "MySQL",
      "GCP",
    ],
    impact: "500+ successful errands, 98% client satisfaction",
    image: "/projects/errands.png",
    category: "Logistics",
  },
  {
    name: "Repairhub",
    url: "https://www.repairhub.co.ke",
    description:
      "Two-sided marketplace connecting clients with electronics technicians",
    tech: [
      "Next.js 16",
      "TailwindCSS",
      "Flask",
      "Payment Integration",
      "JWT Auth",
      "MySQL",
      "GCP",
    ],
    impact: "Real-time job matching, rating system",
    image: "/projects/repairhub.png",
    category: "Marketplace",
  },
  {
    name: "Tizi Plus Kenya",
    url: "https://www.tiziplus.ke",
    description: "Fitness tracking platform with subscription management",
    tech: [
      "Next.js 16",
      "TailwindCSS",
      "Flask",
      "Payment Integration",
      "JWT Auth",
      "MySQL",
      "GCP",
    ],
    impact: "Full gym/client management system",
    image: "/projects/tizi.png",
    category: "Health & Fitness",
  },
  {
    name: "EABeats Official",
    url: "https://www.eabeatsofficial.co.ke",
    description:
      "Website for Music Producers to sell beats. Music lovers are also able to sign up, listen to and purchase their favorite beats.",
    tech: [
      "Next.js 16",
      "TailwindCSS",
      "Flask",
      "Payment Integration",
      "JWT Auth",
      "MYSQL",
      "GCP",
    ],
    impact: "1,000+ daily transactions handled",
    image: "/projects/eabeats.png",
    category: "E-Commerce",
  },
  {
    name: "Gemify Africa",
    url: "https://www.gemify.africa",
    description:
      "Discovery & booking platform connecting 50+ unique venues across Africa",
    tech: [
      "Next.js 16",
      "TailwindCSS",
      "Flask",
      "Payment Integration",
      "JWT Auth",
      "MySQL",
      "GCP",
    ],
    impact: "200+ active listings, real-time booking system",
    image: "/projects/gemify.png",
    category: "Marketplace",
  },
];
